sudo: false
language: python
python:
- 3.6
branches:
  only:
  - main # build main branch only

env:
  global:
  - ALI_IP: 8.136.13.58

addons:
  ssh_known_hosts: 
  - 8.136.13.58

before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

script:
- ssh voidking@${ALI_IP} "cd /opt/voidking/ && git pull"

after_success:
- echo "deploy success"